NewsNote/NewsNote/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

NewsNote/urls.py
from django.contrib import admin
from django.urls import path, include

from news.views import subscriptions

from news.views import subscribe

urlpatterns = [
   path('admin/', admin.site.urls, name='admin'),
   path("accounts/", include("allauth.urls")),
   path('news/', include('news.urls')),
   path('subscriptions/', subscriptions, name='subscriptions'),
   path('subscriptions/<int:pk>/subscribe/', subscribe, name='subscribe'),
]

news/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import (
   PostsList, PostDetail, PostSearch, PostCreate, PostUpdate, PostDelete,
   CategoryListView, subscribe, subscriptions
)

urlpatterns = [
   path('', cache_page(60)(PostsList.as_view()), name=' '),
   path('<int:pk>', cache_page(60*5)(PostDetail.as_view()), name='post_detail'),
   path('search/', PostSearch.as_view(), name='post_search'),
   path('create/', PostCreate.as_view(), name='post_create'),
   path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('categories/<int:pk>/', CategoryListView.as_view(), name='category_list'),
   path('categories/<int:pk>/subscribe/', subscribe, name='subscribe'),

]

NewsNote/news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum

# Create your models
class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    def update_rating(self):
        posRat = self.post_set.aggregate(postRat=Sum('rating'))
        pRat = 0
        pRat += posRat.get('postRat') if posRat.get('postRat') else 0

        commentRat = self.authorUser.comment_set.aggregate(commRat=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commRat') if commentRat.get('commRat') else 0

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)

class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES=(
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through="PostCategory")
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating +=1
        self.save()

    def dislike(self):
        self.rating -=1
        self.save()

    def preview(self):
        return self.text[0:123] + '...'

class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

news/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse
from django.core.cache import cache

# Create your models
class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE)
    ratingAuthor = models.SmallIntegerField(default=0)

    class Meta:
        ordering = ['id']

    # def __str__(self):
    #     return self.authorUser



    def update_rating(self):
        posRat = self.post_set.aggregate(postRat=Sum('rating'))
        pRat = 0
        pRat += posRat.get('postRat') if posRat.get('postRat') else 0

        commentRat = self.authorUser.comment_set.aggregate(commRat=Sum('rating'))
        cRat = 0
        cRat += commentRat.get('commRat') if commentRat.get('commRat') else 0

        self.ratingAuthor = pRat * 3 + cRat
        self.save()

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    subscribers = models.ManyToManyField(User, blank=True, related_name='categories')


    def __str__(self):
        return self.name

    class Meta:
        ordering = ['id']


class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'
    CATEGORY_CHOICES=(
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    )

    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    categoryType = models.CharField(max_length=2, choices=CATEGORY_CHOICES, default=ARTICLE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    postCategory = models.ManyToManyField(Category, through="postCategory")
    title = models.CharField(max_length=128)
    text = models.TextField()
    rating = models.SmallIntegerField(default=0)
    is_published = models.BooleanField(default=True)
    # category = models.ForeignKey(to='Category', on_delete=models.CASCADE, related_name='posts')

    def preview(self):
        preview = f'{self.text[:124]} ...'
        return preview

    # def __str__(self):
    #     return f'{self.title} | {self.author}'


    def __str__(self):
        return self.title
    def like(self):
        self.rating +=1
        self.save()

    def dislike(self):
        self.rating -=1
        self.save()



    # def get_absolute_url(self):
    #     return reverse('post_detail', args=[str(self.id)])

    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return f'/news/{self.id}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
        cache.delete(f'post-{self.pk}')  # затем удаляем его из кэша, чтобы сбросить его

    class Meta:
        ordering = ['dateCreation', 'title']

class PostCategory(models.Model):
    postThrough = models.ForeignKey(Post, on_delete=models.CASCADE)
    categoryThrough = models.ForeignKey(Category, on_delete=models.CASCADE)
    class Meta:
        ordering = ['id']



class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    dateCreation = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    class Meta:
        ordering = ['id']



class Subscriber(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post


class PostForm(forms.ModelForm):
    text = forms.CharField(min_length=20)

    class Meta:
        model = Post
        fields = ['author', 'categoryType', 'postCategory', 'title', 'text']

    def clean(self):
        cleaned_data = super().clean()
        text = cleaned_data.get("text")
        title = cleaned_data.get("title")

        if title == text:
            raise ValidationError(
                "Описание не должно быть идентично названию."
            )

        return cleaned_data

NewsNote/news/views.py
from django.shortcuts import render

# Create your views here.

news/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy
from django.views.decorators.cache import cache_page
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView
)

from .forms import PostForm
from .models import *
from datetime import datetime
from .filters import PostFilter
from django.contrib.auth.decorators import login_required
from django.core.cache import cache
import logging


logger = logging.getLogger(__name__)

DEFAULT_FROM_EMAIL = "Zela52@yandex.ru"


# Create your views here.
class PostsList(ListView):

    model = Post
    ordering = '-dateCreation'
    template_name = 'news.html'
    context_object_name = 'posts'
    paginate_by = 3  # вот так мы можем указать количество записей на странице

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # К словарю добавим текущую дату в ключ 'time_now'.
        context['time_now'] = datetime.utcnow()
        context['next_sale'] = "СКИДКА на новостную подписку уже завтра!"
        return context


class PostDetail(DetailView):
    # Модель всё та же, но мы хотим получать информацию по отдельному товару
    model = Post
    # Используем другой шаблон — product.html
    template_name = 'post.html'
    # Название объекта, в котором будет выбранный пользователем продукт
    context_object_name = 'post'
    queryset = Post.objects.all()


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        context['time_now'] = datetime.utcnow()
        # context['next_sale'] = "СКИДКА на новостную подписку уже завтра!"
        return context


    def get_object(self, *args, **kwargs):  # переопределяем метод получения объекта, как ни странно
        obj = cache.get(f'post-{self.kwargs["pk"]}', None)
        # кэш очень похож на словарь, и метод get действует так же. Он забирает значение по ключу, если его нет, то забирает None.

        # если объекта нет в кэше, то получаем его и записываем в кэш
        if not obj:
            obj = super().get_object(queryset=self.queryset)
            cache.set(f'post-{self.kwargs["pk"]}', obj, 5)

        return obj

class PostSearch(ListView):
    model = Post
    ordering = 'title'
    template_name = 'news_search.html'
    context_object_name = 'search'

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Добавляем в контекст объект фильтрации.
        context['filterset'] = self.filterset
        context['time_now'] = datetime.utcnow()
        return context

class PostCreate(PermissionRequiredMixin, CreateView):
    permission_required = ('news.add_post',)
    form_class = PostForm
    model = Post
    template_name = 'news_create.html'


class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('news.change_post',)
    form_class = PostForm
    model = Post
    template_name = 'news_create.html'


class PostDelete(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('posts_list')


class CategoryListView(PostsList):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news_list'


    def get_queryset(self):
        self.postCategory = get_object_or_404(Category, id=self.kwargs['pk']) #получили 1 категорию
        queryset = Post.objects.filter(postCategory=self.postCategory).order_by('-dateCreation') #(queryset)набор запросов к 1 категории
        return queryset #все статьи к этой категории

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.postCategory.subscribers.all()
        context['postCategory'] = self.postCategory
        return context

@login_required
def subscribe(request, pk):
    user = request.user
    postCategory = Category.objects.get(id=pk)
    postCategory.subscribers.add(user)


    message = 'Вы успешно подписались на рассылку новостей категории'
    return render(request, 'subscribe.html', {'postCategory': postCategory, 'message': message})




from django.contrib.auth.decorators import login_required
from django.db.models import Exists, OuterRef
from django.shortcuts import render
from django.views.decorators.csrf import csrf_protect
from .models import Subscriber, Category


@login_required
@csrf_protect
def subscriptions(request):
    if request.method == 'POST':

        category_id = request.POST.get('category_id')
        category = Category.objects.get(id=category_id)
        action = request.POST.get('action')

        if action == 'subscribe':
            Subscriber.objects.create(user=request.user, category=category)
        elif action == 'unsubscribe':
            Subscriber.objects.filter(
                user=request.user,
                category=category,
            ).delete()

    categories_with_subscriptions = Category.objects.annotate(
        user_subscribed=Exists(
            Subscriber.objects.filter(
                user=request.user,
                category=OuterRef('pk'),
            )
        )
    ).order_by('name')
    return render(
        request,
        'subscriptions.html',
        {'categories': categories_with_subscriptions},
    )

templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

<!-- Название у нас будет News -->
{% block title %}
News
{% endblock title %}

<!-- В контенте на странице мы выводим Все новости -->
{% block content %}
    <h1>Все новости </h1>
    <h3>{{ time_now|date:'d M Y' }}</h3>

{# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.news.add_post %}
    <a href="{% url 'post_create' %}" class="btn btn-secondary btn-sm">Добавить новость</a>
    {% endif %}


<h3> {{ next_sale|default_if_none:"Чуть позже сообщим о свежих новостях!" }} </h3>


    {% if is_not_subscriber %}
       <p class="text-center"><a href="{% url 'subscribe' postCategory.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}


<hr>
   {% if category_news_list %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
               <td>Изменить/Удалить</td>
               <td>Категории</td>
           </tr>

           {% for post in category_news_list %}
           <tr>


               <td>{{ post.title|censor }}</td>
               <td>{{ post.dateCreation }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>

               <td>
                    {% if perms.news.change_post %}
                        <a href="{% url 'post_update' post.id %}" class="btn btn-secondary btn-sm">Изменить</a>
                    {% endif %}

                    {% if perms.news.delete_post %}
                        <a href="{% url 'post_delete' post.id %}" class="btn btn-secondary btn-sm">Удалить</a>
                    {% endif %}
               </td>

               <td> {% for postCategory in post.postCategory.all %}
                        <a href="{% url 'category_list' postCategory.id %}" class="btn btn-secondary btn-sm">{{ postCategory }}</a>
                    {% endfor %}
               </td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
 {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуйте! Новые статьи за последнюю неделю!</h2>
<ul>
  {% for post in posts %}
    <li><a href="{{ link }}{{ post.get_absolute_url  }}">{{ post.title }}</a> </li>
   {% endfor %}
</ul>
</body>
</html>

templates/news.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load cache %}
{% cache 30 title %}
<!-- Название у нас будет News -->
{% block title %}
News
{% endblock title %}
{% endcache %}
<!-- В контенте на странице мы выводим Все новости -->
{% block content %}
    <h1>Все новости </h1>
    <h3>{{ time_now|date:'d M Y' }}</h3>
{% cache 30 content %}
<h3>Количество всех статей и новостей на странице:</h3> <h3>{{ posts|length }}</h3>
<h3> {{ next_sale|default_if_none:"Чуть позже сообщим о свежих новостях!" }} </h3>
{% endcache %}
{# Теперь будем проверять не request.user.is_authenticated, а конкретные права #}
    {% if perms.news.add_post %}
    <a href="{% url 'post_create' %}" class="btn btn-secondary btn-sm">Добавить новость</a>
    {% endif %}

<hr>
   {% if posts %}
       <table>
           {% cache 30 posts %}
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
               <td>Изменить/Удалить</td>
               <td>Категории</td>
           </tr>
           {% endcache %}

           {% for post in posts %}
           <tr>


               <td>{{ post.title|censor }}</td>
               <td>{{ post.dateCreation }}</td>
               <td>{{ post.text|truncatechars:20|censor }}</td>

               <td>
                    {% if perms.news.change_post %}
                        <a href="{% url 'post_update' post.id %}" class="btn btn-secondary btn-sm">Изменить</a>
                    {% endif %}

                   {% if perms.news.delete_post %}
                   <a href="{% url 'post_delete' post.id %}" class="btn btn-secondary btn-sm">Удалить</a>
                   {% endif %}
               </td>

               <td> {% for postCategory in post.postCategory.all %}
                        <a href="{% url 'category_list' postCategory.id %}" class="btn btn-secondary btn-sm">{{ postCategory }}</a>
                    {% endfor %}
               </td>

           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Новостей нет!</h2>
   {% endif %}
 {# Добавляем пагинацию на страницу #}

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Hовость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% endblock content %}

templates/news_search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
   <h1>Все новости </h1>

   <form action=""  method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Поиск">
   </form>

   <hr>
   <h3>{{ time_now|date:'d M Y' }}</h3>
   {% if search %}
       <table>
           <tr>
               <td>Заголовок</td>
               <td>Дата публикации</td>
               <td>Текст</td>
           </tr>
           {% for post in search %}
           <tr>
               <td><a class="nav-link" href="{% url 'post_detail' post.id %}">{{ post.title|censor }}</a></td>
               <td>{{ post.dateCreation }}</td>
               <td>{{ post.text|censor|truncatechars:21 }}</td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Постов нет!</h2>
   {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

templates/post.html
{% extends 'flatpages/default.html' %}
{% load cache %}
<!-- Название у нас будет posts -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим все товары -->
{% block content %}
{% cache 30 content %}
    <h3>Публикация!</h3>
        <table>
            <tr>
                <h1>{{ post.title }}</h1>
                <h4>{{ post.dateCreation|date:'d M Y' }}</h4>
                <td>{{ post.text}}</td>
            </tr>
        </table>
{% endcache %}
{% endblock content %}

templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новая <a href="{{ Link }}">статья</a> в твоем любимом разделе!</h2>
<p>{{ text }}</p>

</body>
</html>

templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <p>{{ object.text }}</p>
    <input type="submit" value="Удалить" />
</form>
{% endblock content %}

templates/subscribe.html
{% extends 'flatpages/default.html' %}



{% block content %}
  <h1 class="text-center">{{ message }} - {{ postCategory }}</h1>

{% endblock content %}

templates/subscriptions.html
{% extends 'flatpages/default.html' %}

{% block title %}
Subscriptions
{% endblock title %}

{% block content %}
    {% for category in categories  %}
        <p>
            {{ category.name }}
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="category_id" value="{{ category.id }}" />

                {% if category.user_subscribed %}
                    <button disabled>Подписаться</button>
                    <button name="action" value="unsubscribe">Отписаться</button>
                {% else %}
                    <button name="action" value="subscribe">Подписаться</button>
                    <button disabled>Отписаться</button>
                {% endif %}
            </form>
        </p>
    {% endfor %}
{% endblock content %}